# Generated by Django 2.1.5 on 2019-02-01 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DOWNLOAD_TASK',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(default=None, null=True)),
                ('status', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='STORAGE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('file_path', models.TextField(default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.SmallIntegerField(default=0)),
                ('host', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('cat', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('download_task', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='analysis.DOWNLOAD_TASK')),
            ],
        ),
    ]
