# Generated by Django 2.1.5 on 2019-01-27 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_auto_20190127_0959'),
    ]

    operations = [
        migrations.CreateModel(
            name='DOWNLOADER',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('start_at', models.DateTimeField(auto_now_add=True)),
                ('file_path', models.TextField(default=None, null=True)),
                ('status', models.SmallIntegerField(default=0)),
            ],
        ),
    ]
