# Generated by Django 2.1.5 on 2019-01-27 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_downloader'),
    ]

    operations = [
        migrations.RenameField(
            model_name='downloader',
            old_name='start_at',
            new_name='started_at',
        ),
        migrations.AddField(
            model_name='downloader',
            name='finished_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='storage',
            name='status',
            field=models.SmallIntegerField(default=0),
        ),
    ]
