# Generated by Django 2.1.5 on 2019-01-27 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_auto_20190127_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='file_path',
            field=models.TextField(default=None, null=True),
        ),
    ]
