# Generated by Django 2.1.5 on 2019-01-27 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_auto_20190127_1411'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='path',
            new_name='storage',
        ),
    ]
