# Generated by Django 2.1.5 on 2019-01-30 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0006_auto_20190127_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='host',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='storage',
            name='key',
            field=models.CharField(db_index=True, max_length=64),
        ),
    ]
