# Generated by Django 2.1.5 on 2019-01-31 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0008_storage_cat'),
    ]

    operations = [
        migrations.CreateModel(
            name='DOWNLOAD_TASK',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(default=None, null=True)),
                ('status', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='DOWNLOADER',
        ),
        migrations.RemoveField(
            model_name='url',
            name='storage',
        ),
        migrations.DeleteModel(
            name='URL',
        ),
        migrations.AddField(
            model_name='storage',
            name='download_task',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='analysis.DOWNLOAD_TASK'),
        ),
    ]
