# Generated by Django 2.1.5 on 2019-02-01 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0009_auto_20190131_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='key',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
